version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
     # - 9000:9000
      # - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer-net
    restart: always
    
volumes:
  portainer_data:

networks:
  portainer-net:

# Connect: https://your_server_ip:9443 or http://your_server_ip:8000
